<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Questionnaire extends Model {
	public $fillable = [
		'apelido',
		'endereco',
		'cidade',
		'estado',
		'cep',
		'ponto_ref',
		'telefone',
		'data_nascimento',
		'sexo',
		'nome_mae',
		'nome_pai',
		'cond_resid',
		'endereco_pais',
		'cidade_pais',
		'estado_pais',
		'cep_pais',
		'ponto_ref_pais',
		'telefone_pais',
		'estado_civil',
		'raca',
		'orientacao_sex',
		'mora_com',
		'prat_ativ',
		'tem_filhos',

		'ensino_fund',
		'ensino_medio',
		'motivo_curso',
		'cotista',
		'modalidade',
		'turno',
		'inicio_curso',
		'termino_curso',
		'fez_outra_graduacao',
		'fez_outro_tecnico',
		'fez_curso_lingua',
		'recebe_auxilio',
		'acesso_programas',
		'part_proj_ext',
		'faz_estagio',
		'em_que_estagia',
		'valor_estagio',
		'dific_estudos',

		'trabalha',
		'em_que_trabalha',
		'valor_salario',
		'responsavel',
		'saude',
		'nec_educ',
		'deficiencia',
		'limitacao',
		'usa_medic',
		'nome_medic',
		'valor_medic',
		'plano_saude',
		'nome_plano_saude',
		'plano_odontologico',
		'nome_plano_odontologico',
		'resid_familia',
		'tipo_construcao',
		'abastecimento_agua',
		'infra_rua',
		'coleta_lixo',
		'acesso_saude'
	];
}
