<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateQuestionnairesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('questionnaires', function (Blueprint $table) {
            $table->increments('id');
            $table->text('apelido')->nullable();
            $table->text('rua')->nullable();
            $table->integer('numero')->nullable();
            $table->text('bairro')->nullable();
            $table->text('cidade')->nullable();
            $table->text('estado')->nullable();
            $table->text('cep')->nullable();
            $table->text('ponto_ref')->nullable();
            $table->text('telefone_res')->nullable();
            $table->text('cond_resid')->nullable();
            $table->text('fam_rua')->nullable();
            $table->integer('fam_num')->nullable();
            $table->text('fam_bairro')->nullable();
            $table->text('fam_cidade')->nullable();
            $table->text('fam_estado')->nullable();
            $table->text('fam_cep')->nullable();
            $table->text('fam_ponto_ref')->nullable();
            $table->text('fam_tel_resid')->nullable();
            $table->text('fam_celular')->nullable();
            $table->text('estado_civil')->nullable();
            $table->text('etnia')->nullable();
            $table->text('etnia_outros')->nullable();
            $table->text('orient_sex')->nullable();
            $table->text('orient_sex_outros')->nullable();
            $table->text('mora_com')->nullable();
            $table->text('mora_com_outros')->nullable();
            $table->text('possui_filhos')->nullable();
            $table->text('possui_filhos_qtd')->nullable();
            $table->text('possui_filhos_idade')->nullable();
            $table->text('possui_filhos_idade_outros')->nullable();
            $table->text('prat_ativ_fis')->nullable();
            $table->text('prat_ativ_fis_esp')->nullable();
            $table->text('prat_ativ_fis_freq')->nullable();
            $table->text('ens_fund')->nullable();
            $table->text('ens_med')->nullable();
            $table->text('motivo_curso')->nullable();
            $table->text('cotista')->nullable();
            $table->text('cotista_mod')->nullable();
            $table->text('inicio_curso')->nullable();
            $table->text('termino_curso')->nullable();
            $table->text('fez_outro_curso')->nullable();
            $table->text('curso_ingles')->nullable();
            $table->text('curso_frances')->nullable();
            $table->text('curso_espanhol')->nullable();
            $table->text('curso_libras')->nullable();
            $table->text('curso_outro')->nullable();
            $table->text('recebe_alim')->nullable();
            $table->text('recebe_transp')->nullable();
            $table->text('recebe_morad')->nullable();
            $table->text('recebe_mat_did')->nullable();
            $table->text('recebe_creche')->nullable();
            $table->text('recebe_atleta')->nullable();
            $table->text('recebe_cult')->nullable();
            $table->text('recebe_emerg')->nullable();
            $table->text('recebe_viagem')->nullable();
            $table->text('acesso_seg_vid')->nullable();
            $table->text('acesso_farda')->nullable();
            $table->text('acesso_napne')->nullable();
            $table->text('acesso_mat_esc')->nullable();
            $table->text('acesso_resid_est')->nullable();
            $table->text('acesso_aux_perm')->nullable();
            $table->text('acesso_dentista')->nullable();
            $table->text('acesso_enfermeiro')->nullable();
            $table->text('acesso_medico')->nullable();
            $table->text('acesso_nutricao')->nullable();
            $table->text('acesso_psicologia')->nullable();
            $table->text('acesso_serv_soc')->nullable();
            $table->text('acesso_tec_enf')->nullable();
            $table->text('acesso_merenda')->nullable();
            $table->text('acesso_ajuda_ref')->nullable();
            $table->text('part_proj_pesq')->nullable();
            $table->text('part_proj_pesq_valor')->nullable();
            $table->text('faz_estagio')->nullable();
            $table->text('faz_estagio_area')->nullable();
            $table->text('faz_estagio_valor')->nullable();
            $table->text('dific_mat_nat')->nullable();
            $table->text('dific_mat_hum')->nullable();
            $table->text('dific_mat_ling')->nullable();
            $table->text('dific_mat_esp')->nullable();
            $table->text('trabalha')->nullable();
            $table->text('trabalha_onde')->nullable();
            $table->text('trabalha_salario')->nullable();
            $table->text('resp_desp')->nullable();
            $table->text('resp_desp_outros')->nullable();
            $table->text('deficiente')->nullable();
            $table->text('def_visual')->nullable();
            $table->text('def_fis')->nullable();
            $table->text('dev_aud')->nullable();
            $table->text('def_intelect')->nullable();
            $table->text('def_mult')->nullable();
            $table->text('def_amput')->nullable();
            $table->text('def_out')->nullable();
            $table->text('limitacao')->nullable();
            $table->text('lim_visao')->nullable();
            $table->text('lim_locom')->nullable();
            $table->text('lim_gest')->nullable();
            $table->text('lim_obes')->nullable();
            $table->text('lim_fis')->nullable();
            $table->text('nes_educ')->nullable();
            $table->text('nes_superdot')->nullable();
            $table->text('nes_dalt')->nullable();
            $table->text('nes_tdh')->nullable();
            $table->text('nes_alt_hab')->nullable();
            $table->text('nes_hiper')->nullable();
            $table->text('nes_dislex')->nullable();
            $table->text('nes_aut')->nullable();
            $table->text('nes_out')->nullable();
            $table->text('saud_dep')->nullable();
            $table->text('saud_ansied')->nullable();
            $table->text('saud_diab')->nullable();
            $table->text('saud_hipertensao')->nullable();
            $table->text('saud_desnut')->nullable();
            $table->text('saud_fum')->nullable();
            $table->text('saud_dst')->nullable();
            $table->text('saud_drogas')->nullable();
            $table->text('saud_out')->nullable();
            $table->text('uso_medic')->nullable();
            $table->text('uso_medic_qual')->nullable();
            $table->text('uso_medic_valor')->nullable();
            $table->text('plano_saud')->nullable();
            $table->text('plano_saud_qual')->nullable();
            $table->text('plano_saud_valor')->nullable();
            $table->text('plano_odont')->nullable();
            $table->text('plano_odont_qual')->nullable();
            $table->text('plano_odont_valor')->nullable();
            $table->text('tipo_morad')->nullable();
            $table->text('tipo_morad_fin_valor')->nullable();
            $table->text('tipo_contrucao')->nullable();
            $table->text('tipo_abast_agua')->nullable();
            $table->text('infraest_rua')->nullable();
            $table->text('infraest_lixo')->nullable();
            $table->text('acesso_saude')->nullable();
            $table->text('ben_bolsa_familia')->nullable();
            $table->text('ben_bolsa_familia_valor')->nullable();
            $table->text('ben_loas')->nullable();
            $table->text('ben_bolsa_perm')->nullable();
            $table->text('ben_mcmv')->nullable();
            $table->text('ben_ref_ag')->nullable();
            $table->text('ben_sntp')->nullable();
            $table->text('ben_remedio')->nullable();
            $table->text('ben_jov_aprend')->nullable();
            $table->text('ben_cam_esc')->nullable();
            $table->text('ben_gar_safra')->nullable();
            $table->text('ben_assist_est')->nullable();
            $table->text('ben_prouni')->nullable();
            $table->text('ben_pronatec')->nullable();
            $table->text('ben_mais_med')->nullable();
            $table->text('ben_luz_pt')->nullable();
            $table->text('ben_cist_pt')->nullable();
            $table->text('ben_mer_esc')->nullable();
            $table->text('ben_outros')->nullable();

            $table->integer('user_id')->unsigned()->nullable();
            $table->foreign('user_id')->references('id')->on('users');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('questionnaires');
    }
}
